In [1]:
import numpy as np

In [3]:
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [8]:
arr3 =np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr3 =np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr3 =np.identity(5)
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr3 =np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])